apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "klusterz-example"
  namespace: "default"
  labels:
    app: klusterz-example
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: klusterz-example
  template:
    metadata:
      labels:
        app: klusterz-example
    spec:
      containers:
      - name: klusterz-example
        image: "rutledgepaulv/klusterz-example:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        - containerPort: 8443
        env:
        - name: KUBERNETES_API
          value: "https://10.96.0.1"
        - name: RING_PORT
          value: "3000"
        - name: KLUSTERZ_PORT
          value: "8443"
        - name: KLUSTERZ_SECRET
          value: "alphabetsoup!"